### ISSUE TITLE
npm run lint fails: eslint.config.js requires packages that are not in package.json

### ISSUE THREAD

**Issue by Nate314** [Nate314/site#71]
Pre-existing (not introduced by PR #70), found while checking the unit tests and lint for that PR.

`npx ng lint` stops with `Error when running ESLint: Cannot find module 'typescript-eslint'`. `eslint.config.js` (lines 3 and 4) requires the `typescript-eslint` and `angular-eslint` meta packages, but `package.json` only declares the scoped `@typescript-eslint/eslint-plugin`, `@typescript-eslint/parser` and `@angular-eslint/*` packages. Neither meta package is installed.

**Fix:** either add `typescript-eslint` and `angular-eslint` to devDependencies (then confirm `npm audit` stays at 0 high/critical and `npm ci` still works), or rewrite the flat config to use the scoped packages that are already declared. Then fix whatever lint errors it reports, and decide whether to run lint in CI.
